fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
wcs_wild_exchange:
    resource: "@WCSWildExchangeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
