wcs_wild_exchange_question:
    resource: "@WCSWildExchangeBundle/Resources/config/routing/question.yml"
    prefix:   /question

wcs_wild_exchange_homepage:
    path:     /
    defaults: { _controller: WCSWildExchangeBundle:Homepage:index }

wcs_wild_exchange_user_edit:
    path:     user/edit
    defaults: { _controller: WCSWildExchangeBundle:User:edit }

wcs_wild_exchange_user_show:
    path:     user/show
    defaults: { _controller: WCSWildExchangeBundle:User:show }

wcs_wild_exchange_reponse:
    resource: "@WCSWildExchangeBundle/Resources/config/routing/reponse.yml"
    prefix:   /reponse
